version: '3.7'
services:

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    depends_on:
      - mariadb

  php:
    image: php
    ports:
      - "8180:80"
    depends_on:
      - mariadb
      - mailhog
    volumes:
      - .:/var/www/html